mod_version = 2.3.0
mod_name = Trigger Happy Ghast
mod_id = ghastfire73
mod_authors = Bowser_The_Boss
mod_licence = All Rights Reserved
mod_group_id = xyz.quazaros
mod_description=Shoot fireballs through the happy ghast

version_control = https://github.com/UY-scuti73/Trigger_Happy_Ghast-Mod
discord_link = https://discord.gg/zHzFgWX8KW