name: Attach Files to Release

on:
  release:
    types: [created]

jobs:
  upload-assets:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        with:
          files: "Output Builds/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}